variable "env" {}
variable "vpc_cidr" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "azs" {}
variable "default_vpc_id" {}
variable "account_id" {}
variable "default_vpc_cidr" {}
variable "default_rt_id" {}
variable "instance_type" {}
variable "min_size" {}
variable "max_size" {}
variable "desired_capacity" {}
variable "workstation_node_cidr" {}
variable "rds_instance_class" {}