variable "env" {}
variable "vpc_cidr" {}
variable "public_subnets" {}
variable "private_subnets" {}
variable "azs" {}
variable "default_vpc_id" {}
variable "account_id" {}
variable "default_vpc_cidr" {}
variable "default_rt_id" {}
variable "alb-type" {}
variable "internal" {}
variable "vpc_id" {}
variable "alb_sg_allow_cidr" {}